# Set initial pitch (degrees)
pitch = 0.0
# Set initial yaw (degrees)
yaw = 0.0
# Set camera field-of-view angle (degrees)
fov = 45.0
# Set distance between camera and box (L)
distance = 2.0
# Set window width (pixels) [default: 600]
width = 600
# Set window height, if different from width.
# height = 600
# When finished, pause for FRAMES frames, then loop. Do not set for no loop.
# pauseloop = 12
# Continuous box rotation (angle / frame)
rotate = 0.0
# sets maximum framerate of drawing, independent of actual frames.
framerate = 24.0
# Rate of drawing frames.
fps = 2.0
