# Set initial pitch (degrees)
pitch = 60.0
# Set initial yaw (degrees)
yaw = 45.0
# Set camera field-of-view angle (degrees)
fov = 34.0
# Set distance between camera and box (L)
distance = 3.0
# Set window width (pixels) [default: 600]
width = 1024
# Set window height, if different from width.
height = 1024
# When finished, pause for FRAMES frames, then loop. Do not set for no loop.
pauseloop = 48.0
# Continuous box rotation (angle / frame)
rotate = 1.0
# sets maximum framerate of drawing, independent of actual frames.
framerate = 24.0
# Rate of drawing frames.
fps = 12.0
