sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta

# from kiss3d
before_install:
  # This ppa provides cmake 2.8.11, which travis doesn't have yet
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
install:
  - sudo apt-get install cmake
  - sudo apt-get install libXxf86vm-dev
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.0.3
  - cmake -DBUILD_SHARED_LIBS=ON
  - make
  - sudo make install
