[package]

name = "parview"
version = "0.2.0"
authors = [ "wendell.smith@yale.edu" ]

[dependencies]
docopt = "*"
nalgebra = "*"
rustc-serialize = "*"
rand = "*"
glfw = "*"

[dependencies.kiss3d]
git = "https://github.com/sebcrozet/kiss3d"

[[bin]]
name = "parviewer"

[dependencies]
flate2 = "*"
