[package]

name = "parview"
version = "0.1.0"
authors = [ "wendell.smith@yale.edu" ]

[dependencies.kiss3d]

git = "https://github.com/sebcrozet/kiss3d.git"

[dependencies.docopt]
git = "https://github.com/burntsushi/docopt.rs"

[dependencies.docopt_macros]
git = "https://github.com/burntsushi/docopt.rs"

[dependencies.flate2]
git = "https://github.com/alexcrichton/flate2-rs"

[[bin]]
name = "parviewer"
