[package]

name = "parview"
version = "0.1.0"
authors = [ "wendell.smith@yale.edu" ]

[dependencies]
docopt = "*"
nalgebra = "*"
rustc-serialize = "*"
rand = "*"

[dependencies.glfw]
# Taken from kiss3d/Cargo.toml
git = "https://github.com/bjz/glfw-rs"
default-features = false

[dependencies.kiss3d]
git = "https://github.com/sebcrozet/kiss3d"

[[bin]]
name = "parviewer"

[dependencies]
flate2 = "*"
