[package]

name = "parview"
version = "0.3.0"
authors = [ "wendell.smith@yale.edu" ]

[dependencies]
docopt = "*"
nalgebra = "*"
kiss3d = "*"
rand = "*"
glfw = "*"
flate2 = "*"
serde = "*"
toml = "*"
